### ISSUE TITLE
Trading fee / Confirm buy or sell popup

### ISSUE THREAD

**Issue by Dinobotta** [peatio/peatio#412]
Can anyone add a display of the trading fee in the Trading platform above the Total. 

Also add a popup to confirm a buy or sell order.

**Comment by lgn21st** [comment]
@Dinobotta It is on our plan, but not very high priority, because the Peatio project is extracted from yunbi.com and Yunbi is totally free for trading, deposit or withdrawal, so we do not need this feature, the free period will end at sometime this year, and then well add this feature at the moment.
