### ISSUE TITLE
Running a cluster/HA mode

### ISSUE THREAD

**Issue by vedrankr** [peatio/peatio#423]
Hi,

I was wondering if, and to what extent, the app supports running in a high availability configuration.

Things we would like to do:

1. Running a RabbitMQ cluster and mirroring individual queues across the nodes
2. Running multiple instances of the daemons and matching engines

Are these things somewhat supported?

**Comment by ooowos45653hs** [comment]
hi,

Tell me more, what do you plan ? 

Of course, if you intend to offer 50 altcoins, then it would be a good idea to have multiple instances of deposit daemons. They could run on different servers. But these deposit daemons should be exclusive for each cryptocoin. Meaning, one deposit daemon for altcoin a - m, and another deposit daemon for altcoin n - z... But of course all of these daemons need to access the peatio production database. That access to that database needs to be always ACID conform. This is extremely important. Meaning, no transaction in limbo lost.. In financial industry thats very important. A MongoDB cluster for example would be very bad idea, because its not ACID conform. Transactions would get lost. As long as these database manipulations (like deposit, withdraw, matching) are really ACID, its good to use!

If you have ideas, please share with us.

**Comment by vedrankr** [comment]
We are not planning on offering 50 altcoins. In the financial industry it is pretty standard to run exchanges in the [HA mode](https://en.wikipedia.org/wiki/High-availability_cluster) in order to minimize downtime when one or more machines go down.

Typically you have multiple instances of the matching engine with the same internal state. That way when one machine goes down, the exchange is still processing orders. This is achieved via state replication across the cluster. The messaging bus (RabbitMQ in this case) is also typically run clustered, so that one node going down doesn't impact the rest of the operation.

How is that handled in Peatio? Or is everything meant to run in a singular configuration?

**Comment by janx** [comment]
You need customization to replicate matching, while trade execution/settlement daemon can be replicated out of box.
