### ISSUE TITLE
Run server background

### ISSUE THREAD

**Issue by saravanan95** [peatio/peatio#490]
Help me to run server in background in ubuntu. I have used 'rails server -d' command  but some pages are not working.

**Comment by tkembo** [comment]
Nginx is what makes it run the background. You don't need to run 'rails server -d' when you're deploying to a server.

Did you follow these instructions: https://github.com/peatio/peatio/blob/master/doc/deploy-production-server.md

**Comment by saravanan95** [comment]
I followed these steps https://github.com/peatio/peatio/blob/master/doc/setup-local-ubuntu.md

**Comment by tkembo** [comment]
Hi. That's where your problem is. Those instructions are for running Peatio on your home desktop or laptop where do you don't want to have a dedicated server so you use the built in web server that comes with rails 'ails server -d'. On the server however, you want to automate stuff and you want to use a dedicated web sever that's always running in the background. Nginx in this case. You should start again but following these instructions: https://github.com/peatio/peatio/blob/master/doc/deploy-production-server.md

**Comment by saravanan95** [comment]
Hi. Thanks for the solution.
