### ISSUE TITLE
Funds not working

### ISSUE THREAD

**Issue by longpq18** [peatio/peatio#527]
I try to install peatio exchange, howerver BitcoinWithdraw and Deposit are not working.
I need help ?

**Comment by tkembo** [comment]
What's not working exactly?

**Comment by longpq18** [comment]
I don't understand desposit bitcoin, where are bitcoin ?
![selection_005](https://cloud.githubusercontent.com/assets/15885041/18122726/f4700194-6f94-11e6-9943-e1464b4b78bb.png)
I cannot create address bitcoin when i click confirm button.

**Comment by tkembo** [comment]
If you can't create a bitcoin address then it's one of 3 things:
1. Your daemons are not running.
2. bitcoind is not running
3. You haven't entered the correct credentials in the currencies.yml configuration file so your Peatio installation cant' connect to bitcoind

You should be able to figure out which the problem is by tailing log/production.log

**Comment by valuead** [comment]
Contact me for help

**Comment by valuead** [comment]
vlad@valuead.com

**Comment by ngockhanh150** [comment]
i can help you Pham Long, please contact me at ngockhanh150@gmail.com

**Comment by longpq18** [comment]
It's works thanks @tkembo

**Comment by dapeng313** [comment]
I need help.
Who can help me with teamviwer or skype?
