### ISSUE TITLE
Adding test coins not updating in funds.

### ISSUE THREAD

**Issue by yatindrarao** [peatio/peatio#633]
https://stackoverflow.com/questions/46907132/how-to-add-bitcoin-in-peatio

BTC not updating after adding test coins.

**Comment by scatterp** [comment]
looks like your problem is with this       blockchain: https://testnet.smartbit.com.au/tx/e9d09a0401080e299c3871ba8e3bf537ab20734567cb86ea7a63d9a025b1a8f3
i dunno where you got that address from??
i guess your not using a modern repo either
try with scatterp/peatio or muhammednagy/peatio 
and discuss results in the chat room https://gitter.im/peatio/peatio

**Comment by yatindrarao** [comment]
This is solved as the RabbitMQ configuration looks for localhost and the app server was binded to IP.
